# Data from `r dataset`, compared to all other sites

This document shows how data from **`r dataset`** compares to data from all other sites. This comparison is useful for confirming that units, outliers and variation is similar everywhere.

These data were accessed on `r format(Sys.time(), '%d %B %Y')`


```{r echo=FALSE}
#knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
```

## Size variables

```{r sizes, warning=FALSE, message=FALSE, fig.height=10, fig.width=10}
sizepairs <- physical %>% 
  mutate(focal = ifelse(site == dataset, dataset, "all")) %>% 
  select(maxvol:catchment.area, focal) %>% 
  ggpairs(colour = "focal")

add_theme_to_ggpairs(sizepairs)
```


## Chemical variables -- initial

```{r chem_initial, warning=FALSE, message=FALSE, fig.height=10, fig.width=10}
sizepairs <- physical %>% 
  mutate(focal = ifelse(site == dataset, dataset, "all")) %>% 
  select(turbidity.initial:chlorophyll.initial, focal) %>% 
  ggpairs(colour = "focal")

add_theme_to_ggpairs(sizepairs)
```



